 import { v4 as uuidv4 } from "uuid";

function chillHop() {
    return [
        {
            name: "Kill Bill",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/SOS.png?raw=true",
            artist: "SZA",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/SZA%20-%20Kill%20Bill.mp3?raw=true",
            color: ["#0076d1", "#180070"],
            id: uuidv4(),
            active: true,
            duration: 1000,
            lyric: 0.4,
            valence: 0.6,
            energy: 0.5,
            genre: "R&B",
            album: "SOS",
            explicit: false

        },
        {
            name: "BLUE",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Hit%20me%20hard%20and%20soft%20(Billie).png?raw=true",
            artist: "Billie Eilish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20BLUE.mp3?raw=true",
            color: ["#180070", "#00081f"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.65,
            valence: 0.3,
            energy: 0.35,
            genre: "Alternative",
            album: "Hit me hard and soft",
            explicit: false
        },
        {
            name: "Blank Space",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/1989%20(%20Blank%20Space%20).png?raw=true",
            artist: "Taylor Swift",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Taylor%20Swift%20-%20Blank%20Space.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.73,
            valence: 0.8,
            energy: 0.85,
            genre: "Pop",
            album: "1989",
            explicit: false
        },
        {
            name: "Blinding Lights",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/After%20Hours%20The%20Weeknd.jpg?raw=true",
            artist: "The Weekend",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/The%20Weeknd%20-%20Blinding%20Lights.mp3?raw=true",
            color: ["#CD607D", "#c94043"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.33,
            valence: 1.0,
            energy: 0.95,
            genre: "R&B",
            album: "Afterhour",
            explicit: false
        },
        {
            name: "Ticking",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Zach%20Bryan.png?raw=true",
            artist: "Zach Bryan",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Zach%20Bryan%20-%20Ticking.mp3?raw=true",
            color: ["#205950", "#2ab3bf"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.77,
            valence: 0.1,
            energy: 0.45,
            genre: "Country",
            album: "Zach Bryan",
            explicit: false
        },
        {
            name: "CHIHIRO",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Hit%20me%20hard%20and%20soft%20(Billie).png?raw=true",
            artist: "Billie Eilish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20CHIHIRO.mp3?raw=true",
            color: ["#180070", "#00081f"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.51,
            valence: 0.5,
            energy: 0.65,
            genre: "Alternative",
            album: "Hit me hard and soft",
            explicit: false
        },
        {
            name: "Love Story",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Fearless%20(%20Love%20Story%20).png?raw=true",
            artist: "Taylor Swift",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Taylor%20Swift%20-%20Love%20Story.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.68,
            valence: 0.75,
            energy: 0.85,
            genre: "Country",
            album: "Fearless",
            explicit: false
        },
        {
            name: "Save Your Tears",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/After%20Hours%20The%20Weeknd.jpg?raw=true",
            artist: "The Weekend",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/The%20Weeknd%20-%20Save%20Your%20Tears.mp3?raw=true",
            color: ["#EF8EA9", "#ab417f"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.44,
            valence: 0.55,
            energy: 0.75,
            genre: "R&B",
            album: "Afterhour",
            explicit: false
        },
        {
            name: "SKINNY",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Hit%20me%20hard%20and%20soft%20(Billie).png?raw=true",
            artist: "Billie Eilish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20SKINNY.mp3?raw=true",
            color: ["#180070", "#00081f"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.64,
            valence: 0.25,
            energy: 0.53,
            genre: "Alternative",
            album: "Hit me hard and soft",
            explicit: false
        },
        {
            name: "Peter",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/the%20ttpd%20(%20Peter%20).png?raw=true",
            artist: "Taylor Swift",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Taylor%20Swift%20-%20Peter.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Alternative",
            album: "The Tortured Poets Department",
            explicit: false
        },
        {
            name: "Down Bad",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/the%20ttpd%20(%20Peter%20).png?raw=true",
            artist: "Taylor Swift",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Taylor%20Swift%20-%20Down%20Bad.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "The Tortured Poets Department",
            explicit: true
        },
        {
            name: "Bad Blood",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/1989%20(%20Blank%20Space%20).png?raw=true",
            artist: "Taylor Swift",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Taylor%20Swift%20-%20Bad%20Blood.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Alternative",
            album: "1989",
            explicit: false
        },
        {
            name: "drivers license",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Olivia_SOUR.png?raw=true",
            artist: "Olivia",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/drivers%20license.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Sour",
            explicit: false
        },
        {
            name: "deja vu",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Olivia_SOUR.png?raw=true",
            artist: "Olivia",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/deja%20vu.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Sour",
            explicit: false
        },
        {
            name: "traitor",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Olivia_SOUR.png?raw=true",
            artist: "Olivia",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/traitor.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Sour",
            explicit: false
        },
        {
            name: "making the bed",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Olivia_Guts.png?raw=true",
            artist: "Olivia",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/making%20the%20bed.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Guts",
            explicit: false
        },
        {
            name: "lacy",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Olivia_Guts.png?raw=true",
            artist: "Olivia",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Olivia%20Rodrigo%20-%20lacy.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Guts",
            explicit: false
        },
        {
            name: "bad guy",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/BillieEilish_Wwfawdwg.jpg?raw=true",
            artist: "Billie Eillish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/bad%20guy.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "When we all fall asleep, where do we go ?",
            explicit: false
        },
        {
            name: "Happier than ever",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/BillieEilish_HappierThanEver.jpg?raw=true",
            artist: "Billie Eillish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20Happier%20Than%20Ever.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Happier than ever",
            explicit: false
        },
        {
            name: "Therefore i am",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/BillieEilish_HappierThanEver.jpg?raw=true",
            artist: "Billie Eillish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20Therefore%20I%20Am.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Happier than ever",
            explicit: false
        },
        {
            name: "Billie Bossa Nova",
            cover: 
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/BillieEilish_HappierThanEver.jpg?raw=true",
            artist: "Billie Eillish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20Billie%20Bossa%20Nova.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Happier than ever",
            explicit: false
        },
        {
            name: "Lunch",
            cover:
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Hit%20me%20hard%20and%20soft%20(Billie).png?raw=true",
            artist: "Billie Eilish",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Billie%20Eilish%20-%20LUNCH.mp3?raw=true",
            color: ["#180070", "#00081f"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.64,
            valence: 0.25,
            energy: 0.53,
            genre: "Pop",
            album: "Hit me hard and soft",
            explicit: false
        },
        {
            name: "Houdini",
            cover:  
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Dua_RadicalOptimisim.jpg?raw=true",
            artist: "Dua Lipa",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Dua%20Lipa%20-%20Houdini%20(Official.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Radical Optimism",
            explicit: false
        },
        {
            name: "These Walls",
            cover:  
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Dua_RadicalOptimisim.jpg?raw=true",
            artist: "Dua Lipa",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Dua%20Lipa%20-%20These%20Walls.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Radical Optimism",
            explicit: false
        },
        {
            name: "End Of An Era",
            cover:  
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Dua_RadicalOptimisim.jpg?raw=true",
            artist: "Dua Lipa",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Dua%20Lipa%20-%20End%20Of%20An%20Era.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Radical Optimism",
            explicit: false
        },
        {
            name: "Levitating",
            cover:  
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Dua_FN.png?raw=true",
            artist: "Dua Lipa",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Dua%20Lipa%20-%20Levitating.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Future Nostalgia",
            explicit: false
        },
        {
            name: "Physical",
            cover:  
                "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Dua_FN.png?raw=true",
            artist: "Dua Lipa",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Dua%20Lipa%20-%20Physical.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Future Nostalgia",
            explicit: false
        },
        {
            name: "Royal",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Lorde_PureHeroine.jpg?raw=true",
            artist: "Lorde",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Lorde%20-%20Royals.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Pure Heroine",
            explicit: false
        },
        {
            name: "Buzzcut Season",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Lorde_PureHeroine.jpg?raw=true",
            artist: "Lorde",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Lorde%20-%20Buzzcut%20Season.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Pure Heroine",
            explicit: false
        },
        {
            name: "Hello",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Adele_25.jpg?raw=true",
            artist: "Adele",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Adele%20%20Hello.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "25",
            explicit: false
        },
        {
            name: "When We Were Young",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Adele_25.jpg?raw=true",
            artist: "Adele",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Adele%20When%20We%20Were%20Young.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "25",
            explicit: false
        },
        {
            name: "Love In The Dark",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Adele_25.jpg?raw=true",
            artist: "Adele",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Adele%20%20-%20Love%20in%20the%20Dark.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "25",
            explicit: false
        },
        {
            name: "Rolling In The Deep",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Adele_21.jpg?raw=true",
            artist: "Adele",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Adele_%20Rolling%20In%20The%20Deep.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "21",
            explicit: false
        },
        {
            name: "Set Fire To The Rain",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Adele_21.jpg?raw=true",
            artist: "Adele",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Adele%20Set%20Fire%20To%20The%20Rain.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "21",
            explicit: false
        },
        {
            name: "Work",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Rihana_Anti.jpg?raw=true",
            artist: "Rihanna",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Rihanna%20-%20Work%20ft.%20Drake.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Anti",
            explicit: false
        },
        {
            name: "Love On The Brain",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Rihana_Anti.jpg?raw=true",
            artist: "Rihanna",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Love%20On%20The%20Brain.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Anti",
            explicit: false
        },
        {
            name: "Needed me",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Rihana_Anti.jpg?raw=true",
            artist: "Rihanna",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Needed%20Me.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Anti",
            explicit: false
        },
        {
            name: "Umbrella",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Rihanna_GoodGirlGoneBadReloaded.png?raw=true",
            artist: "Rihanna",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Rihanna%20-%20Umbrella.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Good Girl Gone Bad",
            explicit: false
        },
        {
            name: "Don't Stop the Music",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Rihanna_GoodGirlGoneBadReloaded.png?raw=true",
            artist: "Rihanna",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Rihanna%20-%20Don't%20Stop%20The%20Music.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Good Girl Gone Bad",
            explicit: false
        },
        {
            name: "Flower",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Miley_EndlessSummerVacation.png?raw=true",
            artist: "Miley Cyrus",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Miley%20Cyrus%20-%20Flowers.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Endless Summer Vacation",
            explicit: false
        },
        {
            name: "Jaded",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Miley_EndlessSummerVacation.png?raw=true",
            artist: "Miley Cyrus",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Miley%20Cyrus%20-%20Jaded.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Endless Summer Vacation",
            explicit: false
        },
        {
            name: "River",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Miley_EndlessSummerVacation.png?raw=true",
            artist: "Miley Cyrus",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Miley%20Cyrus%20-%20River.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Endless Summer Vacation",
            explicit: false
        },
        {
            name: "Wrecking Ball",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Miley_Bangerz.jpg?raw=true",
            artist: "Miley Cyrus",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Miley%20Cyrus%20-%20Wrecking%20Ball.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Bangerz",
            explicit: false
        },
        {
            name: "We can't stop",
            cover: "https://github.com/q113pt/MusicLibrary/blob/main/Cover/Miley_Bangerz.jpg?raw=true",
            artist: "Miley Cyrus",
            audio: "https://github.com/q113pt/MusicLibrary/blob/main/Audio/Miley%20Cyrus%20-%20We%20Can't%20Stop.mp3?raw=true",
            color: ["#ffaddd", "#ff007b"],
            id: uuidv4(),
            active: false,
            duration: 1000,
            lyric: 0.84,
            valence: 0.28,
            energy: 0.73,
            genre: "Pop",
            album: "Bangerz",
            explicit: false
        }
        
    ];
}

export default chillHop;